### ISSUE TITLE
Outputs for DIVAnd (and ODV) interactivetool

### ISSUE THREAD

**Issue by Marie59** [usegalaxy-eu/galaxy#170]
Hi @bgruening ! Sorry to bother you. 

I tested ODV(https://github.com/usegalaxy-eu/galaxy/blob/release_23.0_europe/tools/interactive/interactivetool_odv.xml) and DIVAnd(https://github.com/usegalaxy-eu/galaxy/blob/release_23.0_europe/tools/interactive/interactivetool_divand.xml) individually everything seems be working fine ! 

However I started to chain them up and I am an able to get the outputs of neither of the 2 tools in the galaxy history. 
I tested the climate notebook tool (https://github.com/usegalaxy-eu/galaxy/blob/release_23.0_europe/tools/interactive/interactivetool_climate_notebook.xml) with the command put and it works just fine. But I was enable to make it work with divand.
With Yvan we found that in the xml the only difference between climate and divand is `profile="22.05"` and `<command detect_errors="aggressive">`. 

Could it be coming from there or is it a docker issue ? 
Same issue with ODV. 
Am I doing something wrong ? can you help me ? 
Thanks

**Comment by bgruening** [comment]
Does get() work? If put() does not work its most likely a problem with the container.

We install this tool https://github.com/bgruening/galaxy_ie_helpers/ into the container, its on pypi and this library contains the put/get functions. Do you have that installed?

**Comment by bgruening** [comment]
Does get() work? If put() does not work its most likely a problem with the container.

We install this tool https://github.com/bgruening/galaxy_ie_helpers/ into the container, its on pypi and this library contains the put/get functions. Do you have that installed?

**Comment by Marie59** [comment]
> Does get() work? If put() does not work its most likely a problem with the container.
> 
> We install this tool https://github.com/bgruening/galaxy_ie_helpers/ into the container, its on pypi and this library contains the put/get functions. Do you have that installed?

Nope get does not work either. Indeed, I don't remember installing this tool so this is what must be missing. Do you have th e final docker image of DIVAnd that you have modify ? I can add the tool, push the new image and upgrade Divand.

**Comment by Marie59** [comment]
Thanks again for your help ! Concerning ODV I think I know what's missing I'll do a PR today too and you can tell me if you agree with my changes.

**Comment by bgruening** [comment]
@Marie59 sorry that it took that long, can you please retry that tool?

**Comment by Marie59** [comment]
No problem ! I tried both tools and ODV is functioning but there is still nothing in the history when saving in the output a file.
DIVAnd is not working anymore I have this error `docker: Error response from daemon: error while creating mount source path '/cvmfs/data.galaxyproject.org': mkdir /cvmfs/data.galaxyproject.org: permission denied.`

**Comment by Marie59** [comment]
Thank you for your help ! We can talk about it during the week if you' re okay ?
